name: Win32

on: pull_request

jobs:
  CI:
    name: "Continuous Build on Win32"
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
      - name: "Use Node.js 10.x"
        uses: actions/setup-node@master
        with:
          node-version: "10.15.1"
      - uses: actions/setup-python@v1
        with:
          python-version: "2.x"
          architecture: "x86"

      # - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
      #   inputs:
      #     keyfile: ".yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock"
      #     targetfolder: "**/node_modules, !**/node_modules/**/node_modules"
      #     vstsFeed: "$(ArtifactFeed)"

      - name: "Install Dependencies"
        run: yarn --frozen-lockfile

        # condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
      # - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
      #   inputs:
      #     keyfile: ".yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock"
      #     targetfolder: "**/node_modules, !**/node_modules/**/node_modules"
      #     vstsFeed: "$(ArtifactFeed)"
      #   condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))

      - name: "Download Electron"
        run: yarn gulp electron
      - name: "Run Hygiene Checks"
        run: yarn gulp hygiene --skip-tslint
      - name: "Run TSLint Checks"
        run: yarn gulp tslint
      - name: "Run Monaco Editor Checks"
        run: yarn monaco-compile-check
      - name: "Compile Sources"
        run: yarn compile
      - name: "Download Built-in Extensions"
        run: yarn download-builtin-extensions
      - name: "Run Unit Tests"
        run: .\scripts\test.bat --tfs "Unit Tests"
      - name: "Run Integration Tests"
        run: .\scripts\test-integration.bat --tfs "Integration Tests"
    # - task: PublishTestResults@2
    #   displayName: Publish Tests Results
    #   inputs:
    #     testResultsFiles: "*-results.xml"
    #     searchFolder: "$(Build.ArtifactStagingDirectory)/test-results"
    #   condition: succeededOrFailed()
